
version: 2.1
#orbs:
#  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    working_directory: ~/contracts
    docker:
      - image: circleci/node:10.18.0
      - image: trufflesuite/ganache-cli:v6.7.0
        command: ganache-cli --networkId 50 --accounts 20 -l 19000000 -e 10000000000 -m 'concert load couple harbor equip island argue ramp clarify fence smart topic' -h 0.0.0.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: yarn
      - run:
          name: Lint Contracts
          command: yarn run lint:sol
      - run:
          name: Build repo
          command: yarn build
      - run:
          name: Test Contracts
          command: yarn test
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      #     paths:
      #       - node_modules