
version: 2.1
#orbs:
#  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    working_directory: ~/contracts
    docker:
      - image: circleci/node:10.18.0
      - image: trufflesuite/ganache-cli:v6.7.0
        command: ganache-cli --deterministic -e 300 -p 8545 -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --accounts 30 --allowUnlimitedContractSize
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: yarn
      - run:
          name: Lint Contracts
          command: yarn run lint:sol
      - run:
          name: Build repo
          command: yarn build
      # - run:
      #     name: Test Contracts
      #     command: yarn test
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      #     paths:
      #       - node_modules